# Change these first
owner: androtelema # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: GCMS - www.uni-goettingen.de
    url: https://www.uni-goettingen.de
  - name: Yourls Link-Shortener - cs.ugoe.de
    url: http://cs.ugoe.de
  - name: Stud.IP - studip.uni-goettingen.de
    url: https://studip.uni-goettingen.de/
  - name: Intra-Wiki (Staff only) - intra.informatik.uni-goettingen.de
    url: https://intra.informatik.uni-goettingen.de/wiki/index.php/Main_Page
  - name: Doc-Wiki (Public) - doc.informatik.uni-goettingen.de
    url: https://doc.informatik.uni-goettingen.de/wiki/index.php/Hauptseite
  - name: User Homepages - user.informatik.uni-goettingen.de
    url: https://user.informatik.uni-goettingen.de/~atmg/
  - name: Group - dbis - www.dbis.informatik.uni-goettingen.de
    url: https://www.dbis.informatik.uni-goettingen.de
  - name: Group - swe - www.swe.informatik.uni-goettingen.de
    url: https://www.swe.informatik.uni-goettingen.de
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  #logoUrl: https://raw.githubusercontent.com/androtelema/upptime/master/assets/upptime-icon.svg
  logoUrl: https://raw.githubusercontent.com/androtelema/upptime/master/assets/ifi-logo.png
  name: Upptime
  introTitle: "Open-source availability monitor for some of our web servers"
  introMessage: This is for our [Institute](http://cs.ugoe.de/ifi) and it uses real-time data from a [GitHub repository](https://github.com/androtelema/upptime).
  navbar:
    - title: Status
      href: /upptime/
    - title: The Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
