# Change these first
owner: androtelema # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Gwdg Homepage
    url: https://www.gwdg.de
  - name: Uni-Gcms IfI Homepage
    url: https://www.uni-goettingen.de/de/619480.html
  - name: Yourls Link-Shortener
    url: http://cs.ugoe.de
  - name: Bewerberportal app2.informatik.uni-goettingen.de/cs/2021/wise
    url: https://app2.informatik.uni-goettingen.de/cs/2021/wise
  - name: Intra-Wiki (Staff only)
    url: https://intra.informatik.uni-goettingen.de/wiki/index.php/Main_Page
  - name: Doc-Wiki (public)
    url: https://doc.informatik.uni-goettingen.de/wiki/index.php/Hauptseite
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is an adaption for our **Institute** which uses **real-time** data from our [GitHub repository](https://github.com/androtelema/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
